name: Build and Release (Tauri)

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    name: Build and create Windows release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install dependencies
        run: |
          npm ci

      - name: Install Windows bundler tools (NSIS, WiX)
        if: runner.os == 'Windows'
        run: |
          choco install -y nsis
          choco install -y wixtoolset

      - name: Build Tauri bundle
        env:
          CI: true
        run: |
          npm run tauri build

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body_path: UPDATE.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
